/*Jose Lopez - joseal2
*Partners: Daniel Ao-dao3, Kevin Hu-kwh2
*
*This program is directed by main.c, it's purpose is to generate a 
*random number based on a seed given by the user, then take guesses
*from the user and tell them if the guesses are accurate, and to what
*extent
*/

#include <stdio.h>
#include <stdlib.h>
#include "prog5.h"

//# of guesses made by the user so far
static int guess_number = 0;

//Store the four solutions generated by rand() here
static int solution1;
static int solution2;
static int solution3;
static int solution4;

//This is the seed to generate a random number from 
static int seed;

//This is whatever comes after the seed in the user input
//Will be ignored by the function set_seed()
static char post[2];


/*
 * set_seed -- This function sets the seed value for pseudorandom
 * number generation based on the number the user types.
 * The input entered by the user is already stored in the string seed_str by the code in main.c.
 * This function should use the function sscanf to find the integer seed value from the
 * string seed_str, then initialize the random number generator by calling srand with the integer
 * seed value. To be valid, exactly one integer must be entered by the user, anything else is invalid.
 * INPUTS: seed_str -- a string (array of characters) entered by the user, containing the random seed
 * OUTPUTS: none
 * RETURN VALUE: 0 if the given string is invalid (string contains anything
 *               other than a single integer), or 1 if string is valid (contains one integer)
 * SIDE EFFECTS: initializes pseudo-random number generation using the function srand. Prints "set_seed: invalid seed\n"
 *               if string is invalid. Prints nothing if it is valid.
 */
int set_seed (const char seed_str[])
{
if (sscanf (seed_str, "%d%1s", &seed, post) == 1) //Put the user input into a string, and check that they entered only integers
{
  srand(seed); //Set the seed for rand()
  return 1;
}
printf("set seed: invalid seed \n");
  return 0;
}


/*
 * start_game -- This function is called by main.c after set_seed but before the user makes guesses.
 *               This function creates the four solution numbers using the approach
 *               described in the wiki specification (using rand())
 *               The four solution numbers should be stored in the static variables defined above.
 *               The values at the pointers should also be set to the solution numbers.
 *               The guess_number should be initialized to 1 (to indicate the first guess)
 * INPUTS: none
 * OUTPUTS: *one -- the first solution value (between 1 and 7)
 *          *two -- the second solution value (between 1 and 7)
 *          *three -- the third solution value (between 1 and 7)
 *          *four -- the fourth solution value (between 1 and 7)
 * RETURN VALUE: none
 * SIDE EFFECTS: records the solution in the static solution variables for use by make_guess, set guess_number
 */
void start_game (int* one, int* two, int* three, int* four)
{
  //Set the four solutions to separate random integers between 1-7
  *one   = rand() % 7 +1;
  solution1 = *one;
  *two   = rand() % 7 +1;
  solution2 = *two;
  *three = rand() % 7 +1;
  solution3 = *three;
  *four  = rand() % 7 +1;
  solution4 = *four;
}

/*
 * make_guess -- This function is called by main.c after the user types in a guess.
 *               The guess is stored in the string guess_str.
 *               The function must calculate the number of perfect and misplaced matches
 *               for a guess, given the solution recorded earlier by start_game
 *               The guess must be valid (contain only 4 integers, within the range 1-7). If it is valid
 *               the number of correct and incorrect matches should be printed, using the following format
 *               "With guess %d, you got %d perfect matches and %d misplaced matches.\n"
 *               If valid, the guess_number should be incremented.
 *               If invalid, the error message "make_guess: invalid guess\n" should be printed and 0 returned.
 *               For an invalid guess, the guess_number is not incremented.
 * INPUTS: guess_str -- a string consisting of the guess typed by the user
 * OUTPUTS: the following are only valid if the function returns 1 (A valid guess)
 *          *one -- the first guess value (between 1 and 7)
 *          *two -- the second guess value (between 1 and 7)
 *          *three -- the third guess value (between 1 and 7)
 *          *four -- the fourth color value (between 1 and 7)
 * RETURN VALUE: 1 if the guess string is valid (the guess contains exactly four
 *               numbers between 1 and 7), or 0 if it is invalid
 * SIDE EFFECTS: prints (using printf) the number of matches found and increments guess_number(valid guess)
 *               or an error message (invalid guess)
 *               (NOTE: the output format MUST MATCH EXACTLY, check the wiki writeup)
 */
int make_guess (const char guess_str[], int* one, int* two, int* three, int* four)
{
//These are the four guesses inputted by the user
int w,x,y,z;

//Eight variables that say whether each solution or guess has been "paired"
//If = 0, not paired yet
//If = 1, has been paired, will not be tested against any other solutions/guesses 
int sol1_pair,sol2_pair,sol3_pair,sol4_pair;
int g1_pair,g2_pair,g3_pair,g4_pair;
sol1_pair=0;
sol2_pair=0;
sol3_pair=0;
sol4_pair=0;
g1_pair=0;
g2_pair=0;
g3_pair=0;
g4_pair=0;

//Counts the number of perfect matches
int perf = 0;
//Counts the number of misplaced matches 
int misplaced = 0;

//Check for guesses to be between 7-1, if they aren't return 0
//If all are in range, check for perfect guesses where the guess
//position is the same as the solution position
if ((sscanf (guess_str, "%d%d%d%d%1s", &w, &x, &y, &z, post) == 4)
    && (w >= 1 && w <=7) && (x >= 1 && x <=7)
    && (z >= 1 && z <=7) && (z >= 1 && z <=7))
{
  //Set the guesses in main.c
  *one = w;
  *two = x;
  *three = y;
  *four = z;

  //If the guess is perfect, increment perf, and set the solution and 
  //guess to "already paired" aka 1 aka true
  if(*one == solution1){
    perf++;
    sol1_pair++;
    g1_pair++;
  }
  if(*two == solution2){
    perf++;
    sol2_pair++;
    g2_pair++;
  }
  if(*three == solution3){
    perf++;
    sol3_pair++;
    g3_pair++;
  }
  if(*four == solution4){
    perf++;
    sol4_pair++;
    g4_pair++;
  }

//If the guess isn't already paired, check if it is the same as
//any of the solutions (if they haven't already been paired)
//If they are the same, increment misplaced count and set the solution
//and guess numbers to "already paired"
if (!g1_pair)
{
  if((*one == solution2) && !sol2_pair)
    misplaced += ++sol2_pair + g1_pair++;
  else if((*one == solution3) && !sol3_pair)
    misplaced += ++sol3_pair + g1_pair++;
  else if((*one == solution4) && !sol4_pair)
    misplaced += ++sol4_pair + g1_pair++;
}


if (!g2_pair)
{
  if((*two == solution1) && !sol1_pair)
    misplaced += ++sol1_pair + g2_pair++;
  else if((*two == solution3) && !sol3_pair)
    misplaced += ++sol3_pair + g2_pair++;
  else if((*two == solution4) && !sol4_pair)
    misplaced += ++sol4_pair + g2_pair++;
}

if (!g3_pair)
{
    if((*three == solution1) && !sol1_pair)
      misplaced += ++sol1_pair + g3_pair++;
    else if((*three == solution2) && !sol2_pair)
      misplaced += ++sol2_pair + g3_pair++;
    else if((*three == solution4) && !sol4_pair)
      misplaced += ++sol4_pair + g3_pair++;
}

if (!g4_pair)
{
    if((*four == solution1) && !sol1_pair)
      misplaced += ++sol1_pair + g4_pair++;
    else if((*four == solution2) && !sol2_pair)
      misplaced += ++sol2_pair + g4_pair++;
    else if((*four == solution3) && !sol3_pair)
      misplaced += ++sol3_pair + g4_pair++;
}

//Increment the guess counter and print the results of the function, return 1 to say it was a valid guess 
guess_number++;
printf("With guess %d, you got %d perfect matches and %d misplaced matches.\n", guess_number,perf,misplaced);
return 1;
}
//Return 0 if invalid guess and print invalid guess message 
printf("make_guess: invalid guess\n");
return 0;

}
